---
- name: Install fontconfig
  apt:
    name: fontconfig
    state: present
  become: true

- name: Install nerd shell fonts
  get_url:
    url: "{{ item }}"
    dest: /usr/share/fonts
    mode: "u=rwx,go=rx"
  loop: "{{  shell_fontsÂ  }}"
  become: true
  register: nerd_shell_fonts_added
  notify:
    - Refresh font cache
